language: objective-c
osx_image: xcode7
git:
  submodules: false
branches:
  only:
    - master
script: script/cibuild
notifications:
  email: true
before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
