language: objective-c
osx_image: xcode8
git:
  submodules: false
branches:
  only:
    - master
script: script/cibuild
notifications:
  email: true
before_install:
  - brew update
after_success:
  - bash <(curl -s https://codecov.io/bash)

